name: 01 - Building Blocks
on:
    push:
    workflow_dispatch:
jobs:
    echo-hello:
        runs-on: ubuntu-latest
        name: Say Hello
        steps:
            - run: echo "Hello,World!"
    echo-goodbye:
        runs-on: ubuntu-latest
        steps:
            - name: Failed Step
              run: |
                  echo "I will fail"
                  return 0

            - name: Say goodbye
              run: echo "Goodbye!"
